package ec.gob.registrocivil;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T10:56:45.634-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ConsultaCiudadano",
                  wsdlLocation = "/ConsultaCiudadanoRCPointToPoint.wsdl",
                  targetNamespace = "http://www.registrocivil.gob.ec")
public class ConsultaCiudadano_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.registrocivil.gob.ec", "ConsultaCiudadano");
    public final static QName ConsultaCiudadanoPort = new QName("http://www.registrocivil.gob.ec", "ConsultaCiudadanoPort");
    static {
        URL url = ConsultaCiudadano_Service.class.getResource("/ConsultaCiudadanoRCPointToPoint.wsdl");
        if (url == null) {
            url = ConsultaCiudadano_Service.class.getClassLoader().getResource("/ConsultaCiudadanoRCPointToPoint.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(ConsultaCiudadano_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "/ConsultaCiudadanoRCPointToPoint.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaCiudadano_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCiudadano_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultaCiudadano_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultaCiudadano
     */
    @WebEndpoint(name = "ConsultaCiudadanoPort")
    public ConsultaCiudadano getConsultaCiudadanoPort() {
        return super.getPort(ConsultaCiudadanoPort, ConsultaCiudadano.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCiudadano
     */
    @WebEndpoint(name = "ConsultaCiudadanoPort")
    public ConsultaCiudadano getConsultaCiudadanoPort(WebServiceFeature... features) {
        return super.getPort(ConsultaCiudadanoPort, ConsultaCiudadano.class, features);
    }

}
