package ec.gob.dinardap.interoperabilidad.interoperador;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T10:56:46.666-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://interoperabilidad.dinardap.gob.ec/interoperador/", name = "interoperador")
@XmlSeeAlso({ObjectFactory.class})
public interface Interoperador {

    @WebMethod(action = "http://interoperabilidad.dinardap.gob.ec/interoperador/consultar")
    @RequestWrapper(localName = "consultar", targetNamespace = "http://interoperabilidad.dinardap.gob.ec/interoperador/", className = "ec.gob.dinardap.interoperabilidad.interoperador.Consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://interoperabilidad.dinardap.gob.ec/interoperador/", className = "ec.gob.dinardap.interoperabilidad.interoperador.ConsultarResponse")
    @WebResult(name = "paquete", targetNamespace = "")
    public ec.gob.dinardap.interoperabilidad.interoperador.Paquete consultar(
        @WebParam(name = "parametros", targetNamespace = "")
        ec.gob.dinardap.interoperabilidad.interoperador.Parametros parametros
    ) throws ConsultarFaultException;
}
