package ec.gob.registrocivil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T10:56:45.528-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.registrocivil.gob.ec", name = "ConsultaCiudadano")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaCiudadano {

    @WebMethod(operationName = "BusquedaPorNui", action = "http://www.registrocivil.gob.ec/BusquedaPorNui")
    @RequestWrapper(localName = "BusquedaPorNui", targetNamespace = "http://www.registrocivil.gob.ec", className = "ec.gob.registrocivil.BusquedaPorNui")
    @ResponseWrapper(localName = "BusquedaPorNuiResponse", targetNamespace = "http://www.registrocivil.gob.ec", className = "ec.gob.registrocivil.BusquedaPorNuiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.Ciudadano busquedaPorNui(
        @WebParam(name = "CodigoInstitucion", targetNamespace = "")
        java.lang.String codigoInstitucion,
        @WebParam(name = "CodigoAgencia", targetNamespace = "")
        java.lang.String codigoAgencia,
        @WebParam(name = "Usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "Contrasenia", targetNamespace = "")
        java.lang.String contrasenia,
        @WebParam(name = "NUI", targetNamespace = "")
        java.lang.String nui
    );

    @WebMethod(operationName = "BusquedaPorNuiIndividual", action = "http://www.registrocivil.gob.ec/BusquedaPorNuiIndividual")
    @RequestWrapper(localName = "BusquedaPorNuiIndividual", targetNamespace = "http://www.registrocivil.gob.ec", className = "ec.gob.registrocivil.BusquedaPorNuiIndividual")
    @ResponseWrapper(localName = "BusquedaPorNuiIndividualResponse", targetNamespace = "http://www.registrocivil.gob.ec", className = "ec.gob.registrocivil.BusquedaPorNuiIndividualResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.Ciudadano busquedaPorNuiIndividual(
        @WebParam(name = "CodigoInstitucion", targetNamespace = "")
        java.lang.String codigoInstitucion,
        @WebParam(name = "CodigoAgencia", targetNamespace = "")
        java.lang.String codigoAgencia,
        @WebParam(name = "Usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "Contrasenia", targetNamespace = "")
        java.lang.String contrasenia,
        @WebParam(name = "NUI", targetNamespace = "")
        java.lang.String nui,
        @WebParam(name = "IndividualDactilar", targetNamespace = "")
        java.lang.String individualDactilar
    );

    @WebMethod(operationName = "BusquedaPorNombre", action = "http://www.registrocivil.gob.ec/BusquedaPorNombre")
    @RequestWrapper(localName = "BusquedaPorNombre", targetNamespace = "http://www.registrocivil.gob.ec", className = "ec.gob.registrocivil.BusquedaPorNombre")
    @ResponseWrapper(localName = "BusquedaPorNombreResponse", targetNamespace = "http://www.registrocivil.gob.ec", className = "ec.gob.registrocivil.BusquedaPorNombreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.gob.registrocivil.Ciudadanos busquedaPorNombre(
        @WebParam(name = "CodigoInstitucion", targetNamespace = "")
        java.lang.String codigoInstitucion,
        @WebParam(name = "CodigoAgencia", targetNamespace = "")
        java.lang.String codigoAgencia,
        @WebParam(name = "Usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "Contrasenia", targetNamespace = "")
        java.lang.String contrasenia,
        @WebParam(name = "Apellido1", targetNamespace = "")
        java.lang.String apellido1,
        @WebParam(name = "Apellido2", targetNamespace = "")
        java.lang.String apellido2,
        @WebParam(name = "Nombre1", targetNamespace = "")
        java.lang.String nombre1,
        @WebParam(name = "Nombre2", targetNamespace = "")
        java.lang.String nombre2,
        @WebParam(name = "EdadInicio", targetNamespace = "")
        java.lang.String edadInicio,
        @WebParam(name = "EdadFinal", targetNamespace = "")
        java.lang.String edadFinal,
        @WebParam(name = "Sexo", targetNamespace = "")
        java.lang.String sexo
    );
}
