
package ec.gob.dinardap.interoperabilidad.interoperador;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T10:56:46.611-05:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "consultarFault", targetNamespace = "http://interoperabilidad.dinardap.gob.ec/interoperador/")
public class ConsultarFaultException extends Exception {

    private ec.gob.dinardap.interoperabilidad.interoperador.ConsultarFault consultarFault;

    public ConsultarFaultException() {
        super();
    }

    public ConsultarFaultException(String message) {
        super(message);
    }

    public ConsultarFaultException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ConsultarFaultException(String message, ec.gob.dinardap.interoperabilidad.interoperador.ConsultarFault consultarFault) {
        super(message);
        this.consultarFault = consultarFault;
    }

    public ConsultarFaultException(String message, ec.gob.dinardap.interoperabilidad.interoperador.ConsultarFault consultarFault, java.lang.Throwable cause) {
        super(message, cause);
        this.consultarFault = consultarFault;
    }

    public ec.gob.dinardap.interoperabilidad.interoperador.ConsultarFault getFaultInfo() {
        return this.consultarFault;
    }
}
