package ec.gob.dinardap.interoperacion.interoperadorws.servicio;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T10:56:45.909-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "InteroperadorlImplService",
                  wsdlLocation = "/servicioWebDinardap.wsdl",
                  targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")
public class InteroperadorlImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", "InteroperadorlImplService");
    public final static QName InteroperadorlImplPort = new QName("http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", "InteroperadorlImplPort");
    static {
        URL url = InteroperadorlImplService.class.getResource("/servicioWebDinardap.wsdl");
        if (url == null) {
            url = InteroperadorlImplService.class.getClassLoader().getResource("/servicioWebDinardap.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(InteroperadorlImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "/servicioWebDinardap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InteroperadorlImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InteroperadorlImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InteroperadorlImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InteroperadorlImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InteroperadorlImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InteroperadorlImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InteroperadorlImpl
     */
    @WebEndpoint(name = "InteroperadorlImplPort")
    public InteroperadorlImpl getInteroperadorlImplPort() {
        return super.getPort(InteroperadorlImplPort, InteroperadorlImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InteroperadorlImpl
     */
    @WebEndpoint(name = "InteroperadorlImplPort")
    public InteroperadorlImpl getInteroperadorlImplPort(WebServiceFeature... features) {
        return super.getPort(InteroperadorlImplPort, InteroperadorlImpl.class, features);
    }

}
