package ec.gob.dinardap.interoperacion.interoperadorws.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-03-07T10:56:45.850-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", name = "InteroperadorlImpl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InteroperadorlImpl {

    @WebMethod
    @WebResult(name = "getFichaGeneralResponse", targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", partName = "parameters")
    public GetFichaGeneralResponse getFichaGeneral(
        @WebParam(partName = "parameters", name = "getFichaGeneral", targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")
        GetFichaGeneral parameters
    );
}
